---
- name: Run commands
  ansible.builtin.command:
    cmd: "{{ app_docker_exec }}"
    chdir: "{{ ansistrano_release_path.stdout }}"
  when: item.enabled | default(true)
  loop: "{{ app_docker_commands }}"
