---
- name: Create writable dirs
  ansible.builtin.file:
    state: directory
    path: "{{ ansistrano_release_path.stdout }}/{{ item }}"
    owner: "{{ app_http_user }}"
    group: "{{ app_http_user }}"
  loop: "{{ app_writable_paths + app_writable_paths_add }}"
